# Generated by Django 2.2.4 on 2019-08-30 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_branches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='bank_id',
            new_name='bank',
        ),
        migrations.AlterField(
            model_name='branches',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Banks'),
        ),
    ]
