# Generated by Django 2.2.4 on 2019-09-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_auto_20190901_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Banks'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
